config/routes.rb
Rails.application.routes.draw do
  root 'main_page#index'
   get 'main_page/event_details'
   post 'main_page/login'
   get 'main_page/regs'
   post 'main_page/new_user'
   get 'main_page/clear_session'
   get 'main_page/user_profile'
   get 'main_page/gallery'
   get 'main_page/calendar'
   get 'main_page/event_cal'
   get 'main_page/vspecial_cal'
   get 'main_page/festival_cal'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def index
    @homeApi = HTTParty.get("http://vpad.in/api/vpad/portal/home/")
  end

  def login
    
    @loginApi = HTTParty.post("http://vpad.in/api/vpad/login",
                              :body => {  "lid" => params[:user][:email],
                                          "pwd" => params[:user][:password] }.to_json,
                              :headers => { 'Content-Type' => 'application/json'})
    if @loginApi.parsed_response == "OK"
      session[:access_token] = @loginApi.headers['x-access-token']
      redirect_to controller: 'main_page', action: 'index', :flash => { :success => "Message" }
    else
      redirect_to controller: 'main_page', action: 'index',:flash => {:error => "Not successfull"}
    end

  end

  def event_details
    eid = params[:event_details]

    @event_det = HTTParty.get("http://vpad.in/api/vpad/guide/#{eid}",:headers => {"X-Access-Token" => session[:access_token],'Content-Type' => 'application/json' })
    @event_details = @event_det['data'].first
    @galleryApi = HTTParty.get("http://vpad.in/api/vpad/gallery",:headers => {"X-Access-Token" => session[:access_token],'Content-Type' => 'application/json' })
     
    @abc = @galleryApi['data'].select {|t| t["eid"] == eid }

    @gallery = HTTParty.get("http://vpad.in/api/vpad/gallery/#{@abc.first['sid']}",:headers => {"X-Access-Token" => session[:access_token],'Content-Type' => 'application/json' })
 
  end


  def clear_session
    reset_session
    redirect_to controller: 'main_page', action: 'index'
  end
  
  def user_profile
    @userinfoApi = HTTParty.get("http://vpad.in/api/vpad/userinfo",:headers => {"X-Access-Token" => session[:access_token],'Content-Type' => 'application/json' })
    @user_details = @userinfoApi['data'].first

  end

  def regs
  
  end

  def new_user
    @registerApi = HTTParty.post("http://vpad.in/api/vpad/register",
                                 :body => {  "fname" => params[:new_user][:fname],"lname" => params[:new_user][:lname],"ph" => params[:new_user][:phone],
                                             "email" => params[:new_user][:email],"pwd" => params[:new_user][:password]}.to_json,
                                 :headers => { 'Content-Type' => 'application/json'})
    redirect_to controller: 'main_page', action: 'index'
  end

  def gallery
    eid = params[:eid]

    @galleryApi = HTTParty.get("http://vpad.in/api/vpad/gallery",:headers => {"X-Access-Token" => session[:access_token],'Content-Type' => 'application/json' })
    @abc = @galleryApi['data'].select {|t| t["eid"] == eid }

    @gallery = HTTParty.get("http://vpad.in/api/vpad/gallery/#{@abc.first['sid']}",:headers => {"X-Access-Token" => session[:access_token],'Content-Type' => 'application/json' })

  end

  def calendar
    @calendarApi = HTTParty.get("http://vpad.in/api/vpad/calendar",:headers => {"X-Access-Token" => session[:access_token],'Content-Type' => 'application/json' })
    @calendar_type_hash = @calendarApi["data"].group_by{|item| item['type']}
  end

  def event_cal
    @calendarApi = HTTParty.get("http://vpad.in/api/vpad/calendar",:headers => {"X-Access-Token" => session[:access_token],'Content-Type' => 'application/json' })
    @calendar_type_hash = @calendarApi["data"].group_by{|item| item['type']}
  end

  def vspecial_cal
    @calendarApi = HTTParty.get("http://vpad.in/api/vpad/calendar",:headers => {"X-Access-Token" => session[:access_token],'Content-Type' => 'application/json' })
    @calendar_type_hash = @calendarApi["data"].group_by{|item| item['type']}
  end

  def festival_cal
    @calendarApi = HTTParty.get("http://vpad.in/api/vpad/calendar",:headers => {"X-Access-Token" => session[:access_token],'Content-Type' => 'application/json' })
    @calendar_type_hash = @calendarApi["data"].group_by{|item| item['type']}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vpad</title>
  <link rel="stylesheet" type="text/css" href="/assets/css/style.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/style.css">

  <link rel="stylesheet" href="css/jBox.css" />>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/main_page/_footer.html.erb
<div class="footer1">
	<div class="container clientlogo">
		<div class="col-md-3">
			<img class="img-responsive" src="/assets/Clients-img_1.png">
		</div>
		<div class="col-md-3">
			<img class="img-responsive" src="/assets/Clients-img_2.png">
		</div>
		<div class="col-md-3">
			<img class="img-responsive" src="/assets/Clients-img_3.png">
		</div>
		<div class="col-md-3">
			<img class="img-responsive" src="/assets/Clients-img_4.png">
		</div>
	</div>
</div>
<footer>
<div class="footer2">
	<div class="container subscriberupdat">
		<p>SUBSCRIBER OUR UPDATES</p><input class="youremail" type="text" name="email" placeholder="Your Email"><input type="button" value="Subscribe" class="subscribe_news">
	</div>
</div>
<div class="footer3">
	<div class="container footer3container">
		<div class="col-md-6 contactfooter">
			<h5>CONTACT US</h5>
			<div class="row">
				<div class="col-md-6">
					<ul class="contactdeta">
						<li>
							<span><img src="/assets/loactionnew1.png"></span>
							<p>6100 PHEASANT RUN SEVERNA PARK, MD 20210</p>
						</li>
					</ul>
				</div>
				<div class="col-md-6">
					<ul class="contactdeta">
						<li><span><img src="/assets/emailnew1.png"></span><p>@VPAD.com</p></li>
						<li><span><img src="/assets/callnew1.png"></span><p>+917000021010</p></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="row logorowimg">
				<img src="/assets/logo2.png">
			</div>
			<div class="row">
				<ul class="menu-lft">
					<li><a href="">HOME</a></li>
					<li><a href="">FESTIVALS</a></li>
					<li><a href="">MY EVENTS</a></li>
					<li><a href="">MY GROUPS</a></li>
					<li><a href="">MY PROFILE</a></li>
					<li><a href="">MY CALENDAR</a></li>
				</ul>
			</div>
			<span>&nbsp;</span>
			<div class="row">
				<ul class="social-media clearfix">
			        <li><a href="" class="face"></a></li>
			        <li><a href="" class="twit"></a></li>
			        <li><a href="" class="linkin"></a></li>
			     </ul>
			</div>
		</div>
	</div>
</div>
	<section class="foot-bottom">
     <div class="container">
     <p>Copyright © 2016 <a href="/">VPAD</a> | All right Reserved</p>
     </div> 
     
   </section>
</footer>

app/views/main_page/_header.html.erb
<header class="header" id="sticky_navigation">
  <div class="container-fluid">
    <div class="col-md-12">
      <div class="col-md-3 logo_hms_n_rooms">
        <a href="/"><img class="logo" src="/assets/Vpad-logo.png" alt="logo"></a>
      </div>
      <div class="col-md-9">
        <div class="cont-reg">

          <ul class="cont-reg-ui">
            <li><a href="">Contact</a></li>
      
            <li id="dropdown-1" class="dropdown dropdown-processed drop">
              <% if session[:access_token].blank? %>
                  <a href="/main_page/regs">Register</a>
                  <a class="dropdown-link1 logi" href="#" id="loginPopup">Login</a>
              <%else%>
                  <%= link_to "logout", :controller=> "main_page", :action=> "clear_session", :class => "dropdown-link1 logi" %>
              <%end%>
              <div class="dropdown-content" style="display: none;">
                <div class="loginform">
                  <div class="row conta-form">

                    <%= form_for("user", :url => main_page_login_path) do |f| %>
                        <div class="form-group">
                          <%= f.label :Email, class: 'emaillabel'%>
                          <%= f.text_field :email, class: "form-control emailbox" %><br/>
                        </div>
                        <div class="form-group">
                          <%= f.label :Password, class: "passlabel" %><br/>
                          <%= f.password_field :password, class: "form-control passbox" %><br />
                        </div>
                        <div class="form-group loginsubfor">
                          <p class="pbtn"><%= f.submit 'Sign in', class: "btn btn-login" %></p>
                        </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </li>
          </ul>

          <br>
          <ul class="social_header_part">
            <li><a class="header_notification"></a></li>
            <li><a class="header_facebook"></a></li>
            <li><a class="header_twitt"></a></li>
            <li><a class="header_linkdin"></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="clear"></div>
  <div class="menu_section">
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active dropdown"><a href="" class="">HOME</a></li>
            <% if session[:access_token].blank? %>            
            <%else%>


                <li class="dropdown">
                  <a href="" class="">CALENDAR</a>
                  <ul class="dropdown-menu">
                    <li>
                      <div class="row">
                        <div class="container">
                          <div class="col-sm-4">
                            <ul>
                              <li><b><a href="/main_page/event_cal">EVENT CALENDAR</a></b></li>
                            </ul>
                          </div>
                          <div class="col-sm-4 second_div_padd">
                            <ul>
                              <li><b><a href="/main_page/vspecial_cal">VSPECIAL CALENDAR</a></b></li>
                            </ul>
                          </div>
                          <div class="col-sm-4">
                            <ul>
                              <li><b><a href="/main_page/festival_cal">FESIVAL CALENDAR</a></b></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                  </ul>
                </li>



                <li class="dropdown"><a href="" class="">MY EVENTS</a></li>
                <li class="dropdown" ><a href="/main_page/user_profile" class="">MY PROFILE</a></li>
            <%end%>


          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/main_page/event_details.html.erb
<!DOCTYPE html>
<html>

<body>

<script type="text/javascript" src="/assets/js/jquery.min.js"></script>
<script language=javascript src='http://maps.google.com/maps/api/js'></script>
<script type="text/javascript">
  $(document).ready(function(){
    $(".dropdown-link1").click(function(){
      $(this).toggleClass("intro");
    });
  });
</script>

<%= render :partial => 'header.html.erb'%>

<div class="container-fluid">
  <div>
    <div class="col-md-7 slider2">
      <div id="myCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <img src="<%=@event_details['image']%>" alt="Chania">
          </div>
        </div>
        <a class="left carousel-control " href="#myCarousel1" role="button" data-slide="prev"></a>
        <a class="right carousel-control " href="#myCarousel1" role="button" data-slide="next"></a>
      </div>
    </div>
    <div class="col-md-5 bussinesconf1">
      <div class="bussinesconf">
        <h3><%=@event_details['name']%></h3>
        <span>&nbsp;</span>
        <ul class="evntdate">
          <li>
            <span><img src="/assets/calender.png"></span>
            <p><%= DateTime.parse(@event_details['date']).strftime("%d-%^b-%Y")%> to <%= DateTime.parse(@event_details['enddate']).strftime("%d-%^b-%Y") rescue nil%></p>
          </li>
          <li>&nbsp;</li>
          <li>
            <span><img src="/assets/clock.png"></span>
            <p>Start Time: <%= DateTime.parse(@event_details['date']).strftime("%I:%M%p")%><br>End Time: <%= DateTime.parse(@event_details['date']).strftime("%I:%M%p") rescue nil%></p>
          </li>
          <li>&nbsp;</li>
        </ul>
      </div>
      <h2>EVENT BOOKING WILL BE CLOSED TODAY</h2>
      <h4>So Hurryup! To Buy Tickets.</h4>
      <div class="buytiketsblock"><input type="button" class="btn buy_ticket" value="Buy Tickets"></div>
    </div>
  </div>
</div>
<span>&nbsp;</span>
<div class="container-fluid attendevtcontainer">
  <div class="attndevnt">
    <div class="col-md-3 wouldatevt">
      <p>Would you attend this event?</p>
    </div>
    <div class="col-md-3 yesnomaybe">
      <input type="radio" id="radio03" name="eventattand" checked="checked"><label for="radio03"><span class="vetattd"></span>&nbsp;&nbsp;Yes&nbsp;&nbsp;</label><input type="radio" id="radio04" name="eventattand"><label for="radio04"><span class="vetattd"></span>&nbsp;&nbsp;No&nbsp;&nbsp;</label><input type="radio" id="radio05" name="eventattand"><label for="radio05"><span class="vetattd"></span>&nbsp;&nbsp;May Be</label>
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
      <img src="/assets/star.png">
    </div>
  </div>
</div>
<span>&nbsp;</span>
<div class="container-fluid">
  <div>
    <ul class="nav nav-tabs eventtab">
      <li class="active eventdeltab"><a data-toggle="tab" href="#menu1">Event Details</a></li>
      <li class="eventdeltab"><a data-toggle="tab" href="#menu2">Agenda </a></li>
      <li class="eventdeltab"><a data-toggle="tab" href="#menu3">Venue Details</a></li>
      <li class="eventdeltab"><a data-toggle="tab" href="#menu4">Organizer Details</a></li>
    </ul>

    <div class="tab-content">
      <div id="menu1" class="tab-pane fade in active">
        <div class="business_confrence">
          <%=@event_details['myevent'].html_safe%>
        </div>
      </div>
      <div id="menu2" class="tab-pane fade">
        <%=@event_details['agenda'].html_safe%>
        <span>&nbsp;</span>
      </div>
      <div id="menu3" class="tab-pane fade">
        <div class="col-md-12 menu3">
          <div class="col-md-6">
            <ul class="venudetbk1">
              <li>&nbsp;</li>
              <li>&nbsp;</li>
              <li>
                <p></p>
              </li>
              <li>&nbsp;</li>
              <li>
                <p><ins class="available"></ins></p>
              </li>
              <li>&nbsp;</li>
              <li>
                <p></p>
              </li>
              <li>&nbsp;</li>
              <li>
                <p></p>
              </li>
              <li>&nbsp;</li>
              <li class="sharespan">
                <span><img src="/assets/share.png"></span>
                <a href="http://maps.google.com/?q=<%=@event_details['map'].split(",")[0]%>,<%=@event_details['map'].split(",")[1]%>"><p>GET DIRECTION</p></a>
              </li>
            </ul>
          </div>
          <div class="col-md-6">
            <div id="map" class="adressmap"></div>

          </div>
        </div>
      </div>
      <div id="menu4" class="tab-pane fade">
        <div class="col-md-12 orgnizerdetales">
          <ul class="orgnizerdetail">
            <li>
              <%=@event_details['infodesk'].html_safe%>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<span>&nbsp;</span>
<div class="sponsor">
  <div class="container sponsorblock">
    <h1><u>SPONSOR</u></h1>
    <%=@event_details['sponsors'].html_safe%>
  </div>
</div>
<span>&nbsp;</span>
<div class="container">
  <div class="col-md-7 userreviwblock">
    <div class="user_review">
      <span>&nbsp;</span>
      <h1>USER REVIEW</h1>
      <span>&nbsp;</span>
      <form class="form-horizontal" role="form" method="" action="">
        <div class="form-group">
          <div class="col-sm-12">
            <input type="text" class="form-control userreviewinput" placeholder="Name" id="firstname" name="firstname"  value="">
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12">
            <input type="email" class="form-control userreviewinput" placeholder="Email" id="email" name="email"  value="">
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12">
            <textarea class="form-control userreviewinput" placeholder="Comment here...." rows="6" name="message"></textarea>
          </div>
        </div>
        <span>&nbsp;</span>
        <div class="form-group">
          <div class="col-sm-12 userreviewsubmit">
            <input id="submit" name="submit" type="submit" value="SUBMIT" class="btn btn-userreview">
          </div>
        </div>
      </form>
    </div>
    <span>&nbsp;</span>
    <div class="eventslider">
      <h3><%=link_to "GALLERY", main_page_gallery_path(:eid => @event_details['eid'] )%></h3>

      <div id="myCarousel2" class="carousel slide secondslide" data-ride="carousel">
        <div class="carousel-inner innercarousbg" role="listbox">
          <div class="item active left">
            <div class="row">
              <div class="col-md-12 slidealign">
                <div class="col-md-3 galerslide1">
                  <img class="img-responsive" src="<%= @gallery['data'].sample['tbnail']%>">
                </div>
                <div class="col-md-3 galerslide1">
                  <img class="img-responsive" src="<%= @gallery['data'].sample['tbnail']%>">
                </div>
                <div class="col-md-3 galerslide1">
                  <img class="img-responsive" src="<%= @gallery['data'].sample['tbnail']%>">
                </div>
                <div class="col-md-3 galerslide1">
                  <img class="img-responsive" src="<%= @gallery['data'].sample['tbnail']%>">
                </div>


              </div>
            </div>
          </div>

          <div class="item next left">
            <div class="row">
              <div class="col-md-12 slidealign">
                <div class="col-md-3 galerslide1">
                  <img class="img-responsive" src="<%= @gallery['data'].sample['tbnail']%>">
                </div>
                <div class="col-md-3 galerslide1">
                  <img class="img-responsive" src="<%= @gallery['data'].sample['tbnail']%>">
                </div>
                <div class="col-md-3 galerslide1">
                  <img class="img-responsive" src="<%= @gallery['data'].sample['tbnail']%>">
                </div>
                <div class="col-md-3 galerslide1">
                  <img class="img-responsive" src="<%= @gallery['data'].sample['tbnail']%>">
                </div>
              </div>
            </div>
          </div>
          <a class="right carousel-control " href="#myCarousel2" role="button" data-slide="next"></a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-1"></div>
  <div class="col-md-4">
    <div class="spread_the_word">
      <h1>SPREAD THE WORD</h1>
    </div>
    <div class="sherwityouf">
      <ul class="footsocialicon1">
        <li><img src="/assets/facebook1.png"></li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
        <li><img src="/assets/twiter1.png"></li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
        <li><img src="/assets/youtube.png"></li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
        <li><img src="/assets/linkdin1.png"></li>
      </ul>
      <p>share with your friends & colleagues.</p>
    </div>
    <div class="spread_the_word">
      <h1>SIMILAR EVENTS</h1>
    </div>
    <table class="other_event_table">
      <tbody>
      <tr class="simevtblock"><td><img src="/assets/img1.jpg"></td><td><p class="banartcoll">Banglore Art Collective</p><p><img src="/assets/time.png">22 Jan 2016</p><p><img src="/assets/chat.png">10 comments</p></td></tr>
      <tr class="simevtblock"><td><img src="/assets/img2.jpg"></td><td><p class="banartcoll">Banglore Art Collective</p><p><img src="/assets/time.png">22 Jan 2016</p><p><img src="/assets/chat.png">10 comments</p></td></tr>
      <tr class="simevtblock"><td><img src="/assets/img3.jpg"></td><td><p class="banartcoll">Banglore Art Collective</p><p><img src="/assets/time.png">22 Jan 2016</p><p><img src="/assets/chat.png">10 comments</p></td></tr>
      </tbody></table>
  </div>
</div>
<span>&nbsp;</span>

<%= render :partial => 'footer.html.erb'%>
<script type="text/javascript" src="/assets/js/bootstrap.min.js"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $("#first_project").hover(function(){
      $(".inner_projects").show();
    });
    $("#first_project").mouseleave(function(){
      $(".inner_projects").hide();
    });

    $("#secondproject").hover(function(){
      $(".inner_projects_two").show();
    });
    $("#secondproject").mouseleave(function(){
      $(".inner_projects_two").hide();
    });

    $("#thirdproject").hover(function(){
      $(".inner_projects_three").show();
    });
    $("#thirdproject").mouseleave(function(){
      $(".inner_projects_three").hide();
    });
  });

</script>

<script type="text/javascript">
  $(document).ready(function(){

    $('li.dropdown').each(function() {
      var $dropdown = $(this);

      $("a.dropdown-link1", $dropdown).click(function(e) {
        e.preventDefault();
        $div = $("div.dropdown-content", $dropdown);
        $div.toggle();
        $("li.dropdown-content").not($div).hide();
        return false;
      });

    });
    
    $('html').click(function(){
      $("li.dropdown-content").hide();
    });

});
</script>

<script>
  function initialize(){
    var myLatlng = new google.maps.LatLng(12.909694, 77.643218);
    var myOptions = {
      zoom: 14,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    map = new google.maps.Map(document.getElementById("map"), myOptions);
    var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title:"Fast marker"
    });
  }
  google.maps.event.addDomListener(window,'load', initialize);

</script>
</body>
</html>

app/views/main_page/regs.html.erb
<link rel="stylesheet" type="text/css" href="https://rawgit.com/flatlogic/awesome-bootstrap-checkbox/master/awesome-bootstrap-checkbox.css">

<%= render :partial => 'main_page/header.html.erb'%>
<div class="container-fluid regcontener">
  <div class="container">
    <h3>REGISTER WITH US</h3>

    <%= form_for("new_user", url: main_page_new_user_path,:html => {class: "form-horizontal" ,role: "form"}) do |f| %>
        
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :firstname ,class: "col-sm-3 control-label labelalign" %>
            <div class="col-sm-9">
              <%= f.text_field :fname, autofocus: true, class: "form-control reginputclas" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :lastname ,class: "col-sm-3 control-label labelalign" %>
            <div class="col-sm-9">
              <%= f.text_field :lname, autofocus: true, class: "form-control reginputclas" %>
            </div>
          </div>


          <div class="form-group">
            <%= f.label :email,class: "col-sm-3 control-label labelalign" %>
            <div class="col-sm-9">
              <%= f.email_field :email, autofocus: true, class: "form-control reginputclas" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :password ,class: "col-sm-3 control-label labelalign"%>           
            <div class="col-sm-9">
              <%= f.password_field :password, autocomplete: "off", class: "form-control reginputclas" %>
            </div>
          </div>
        </div>


        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :phone ,class: "col-sm-3 control-label labelalign" %>
            <div class="col-sm-9">
              <%= f.text_field :phone, autofocus: true, class: "form-control reginputclas" %>
            </div>
          </div>
    
        </div>

        <div class="form-group">
          <div class="col-md-3"></div>
          <div class="col-sm-9 registerrow">
            <%= f.submit "Sign up",class: "btn btn-register" %>

          </div>
        </div>

        </div>
    <% end %>
    </div>
</div>
</div>

<%#= render "devise/shared/links" %>
<%= render :partial => 'main_page/footer.html.erb'%>
<script type="text/javascript" src="/assets/js/bootstrap.min.js"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $("#first_project").hover(function(){
      $(".inner_projects").show();
    });
    $("#first_project").mouseleave(function(){
      $(".inner_projects").hide();
    });

    $("#secondproject").hover(function(){
      $(".inner_projects_two").show();
    });
    $("#secondproject").mouseleave(function(){
      $(".inner_projects_two").hide();
    });

    $("#thirdproject").hover(function(){
      $(".inner_projects_three").show();
    });
    $("#thirdproject").mouseleave(function(){
      $(".inner_projects_three").hide();
    });
  });

</script>
<script type="text/javascript">
  $(document).ready(function(){

    $('li.dropdown').each(function() {
      var $dropdown = $(this);

      $("a.dropdown-link1", $dropdown).click(function(e) {
        e.preventDefault();
        $div = $("div.dropdown-content", $dropdown);
        $div.toggle();
        $("li.dropdown-content").not($div).hide();
        return false;
      });

    });

    $('html').click(function(){
      $("li.dropdown-content").hide();
    });

  });
</script>
<script type="text/javascript">
  $(document).ready(function() {
    $('.multi_select').multiselect({
      templates: { // Use the Awesome Bootstrap Checkbox structure
        li: '<li><div class="checkbox"><label></label></div></li>'
      }
    });
    $('.multiselect-container div.checkbox').each(function (index) {

      var id = 'multiselect-' + index,
          $input = $(this).find('input');

      // Associate the label and the input
      $(this).find('label').attr('for', id);
      $input.attr('id', id);

      // Remove the input from the label wrapper
      $input.detach();

      // Place the input back in before the label
      $input.prependTo($(this));

      $(this).click(function (e) {
        // Prevents the click from bubbling up and hiding the dropdown
        e.stopPropagation();
      });

    });
  });
</script>